from .base_provider import AIProvider


class MockProvider(AIProvider):

    def generate_code(
        self,
        task,
        requirements,
        architecture
    ):

        project_type = architecture["type"]

        if project_type == "website":

            return {
                "app.py": """from flask import Flask, render_template

app = Flask(__name__)


@app.route("/")
def home():
    return render_template("index.html")


if __name__ == "__main__":
    app.run()
""",

                "templates/index.html": """<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>AURA AI Website</title>
</head>
<body>

<h1>AURA AI Generated Website</h1>

<p>Generated by AURA Coding Brain.</p>

</body>
</html>
""",

                "requirements.txt": "Flask\n"
            }

        if project_type == "software":

            return {
                "main.py": """def main():

    print("AURA AI Generated Software")


if __name__ == "__main__":
    main()
""",

                "requirements.txt": ""
            }

        if project_type == "excel":

            return {
                "main.py": """import pandas as pd


def main():

    data = {
        "Name": ["AURA"],
        "Value": [100]
    }

    df = pd.DataFrame(data)

    print(df)


if __name__ == "__main__":
    main()
""",

                "requirements.txt": "pandas\nopenpyxl\n"
            }

        if project_type == "database":

            return {
                "main.py": """import sqlite3


def main():

    connection = sqlite3.connect("aura.db")

    cursor = connection.cursor()

    cursor.execute(
        "CREATE TABLE IF NOT EXISTS data (id INTEGER PRIMARY KEY)"
    )

    connection.commit()

    connection.close()

    print("AURA AI Database Ready")


if __name__ == "__main__":
    main()
""",

                "requirements.txt": ""
            }

        return {
            "main.py": """def main():

    print("AURA AI Generated Project")


if __name__ == "__main__":
    main()
""",

            "requirements.txt": ""
        }

    def fix_code(
        self,
        task,
        requirements,
        architecture,
        files,
        errors
    ):

        # Mock provider does not perform AI repair.
        # Real AI provider handles autonomous code repair.

        return files