class AICodeGenerator:

    def __init__(
        self,
        provider=None
    ):

        self.provider = provider

    def generate(
        self,
        task,
        requirements,
        architecture
    ):

        if self.provider is not None:

            return self.provider.generate_code(
                task=task,
                requirements=requirements,
                architecture=architecture
            )

        return self._fallback_generation(
            task,
            architecture
        )

    def fix(
        self,
        task,
        requirements,
        architecture,
        files,
        errors
    ):

        if self.provider is not None:

            return self.provider.fix_code(
                task=task,
                requirements=requirements,
                architecture=architecture,
                files=files,
                errors=errors
            )

        return files

    def _fallback_generation(
        self,
        task,
        architecture
    ):

        project_type = architecture["type"]

        if project_type == "website":

            return {
                "app.py": """from flask import Flask, render_template

app = Flask(__name__)


@app.route("/")
def home():
    return render_template("index.html")


if __name__ == "__main__":
    app.run()
""",

                "templates/index.html": """<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>AURA Generated Website</title>
</head>
<body>

<h1>AURA AI Generated Website</h1>

<p>Project generated by AURA Specialist Developer V2.</p>

</body>
</html>
""",

                "requirements.txt": "Flask\n"
            }

        if project_type == "software":

            return {
                "main.py": """def main():
    print("AURA AI Generated Software")


if __name__ == "__main__":
    main()
""",

                "requirements.txt": ""
            }

        if project_type == "excel":

            return {
                "main.py": """import pandas as pd


def analyze_excel(file_path):

    data = pd.read_excel(file_path)

    print(data.head())

    return data


if __name__ == "__main__":
    print("AURA Excel Analyzer")
""",

                "requirements.txt": "pandas\nopenpyxl\n"
            }

        if project_type == "database":

            return {
                "database.py": """import sqlite3


def connect():

    return sqlite3.connect("database.db")


if __name__ == "__main__":

    db = connect()

    print("Database connected.")

    db.close()
""",

                "requirements.txt": ""
            }

        return {
            "main.py": """def main():
    print("AURA AI Generated Project")


if __name__ == "__main__":
    main()
""",

            "requirements.txt": ""
        }