from pathlib import Path


class CodeGenerator:

    def __init__(self, workspace="workspace"):
        self.workspace = Path(workspace)
        self.workspace.mkdir(
            parents=True,
            exist_ok=True
        )

        print("💻 Code Generator: READY")

    # =========================================================
    # GENERATE PYTHON PROJECT
    # =========================================================

    def generate_python_project(
        self,
        project_name,
        description="A Python application"
    ):

        project_path = (
            self.workspace / project_name
        )

        project_path.mkdir(
            parents=True,
            exist_ok=True
        )

        main_code = f'''"""
{project_name}

{description}

Generated by AURA Developer Agent.
"""


def main():

    print("================================")
    print("{project_name}")
    print("================================")
    print()
    print("{description}")
    print()
    print("Generated successfully by AURA.")


if __name__ == "__main__":
    main()
'''

        readme = f'''# {project_name}

## Description

{description}

## Generated By

AURA Developer Agent

## Status

Initial project generated successfully.
'''

        main_file = project_path / "main.py"
        readme_file = project_path / "README.md"

        main_file.write_text(
            main_code,
            encoding="utf-8"
        )

        readme_file.write_text(
            readme,
            encoding="utf-8"
        )

        return {
            "project_path": str(project_path),
            "files": [
                str(main_file),
                str(readme_file)
            ]
        }

    # =========================================================
    # GENERATE SINGLE PYTHON FILE
    # =========================================================

    def generate_python_file(
        self,
        project_name,
        file_name,
        code
    ):

        project_path = (
            self.workspace / project_name
        )

        project_path.mkdir(
            parents=True,
            exist_ok=True
        )

        file_path = (
            project_path / file_name
        )

        file_path.write_text(
            code,
            encoding="utf-8"
        )

        return file_path


# =============================================================
# TEST
# =============================================================

if __name__ == "__main__":

    print()
    print("================================")
    print(" AURA CODE GENERATOR TEST")
    print("================================")
    print()

    generator = CodeGenerator()

    result = generator.generate_python_project(
        project_name="smart_calculator",
        description="A simple smart calculator application."
    )

    print("✅ PROJECT GENERATED")
    print()

    print("📁 Project:")
    print(result["project_path"])

    print()

    print("📄 Files:")

    for file in result["files"]:
        print("   └──", file)

    print()
    print("================================")
    print(" CODE GENERATOR TEST COMPLETE")
    print("================================")
