from pathlib import Path


class CodeGenerationEngine:

    def __init__(self):
        print("💻 Code Generation Engine: READY")

    # =========================================================
    # GENERATE PROJECT
    # =========================================================

    def generate_project(self, plan, project_name):

        if not plan or not plan.get("success"):
            return {
                "success": False,
                "message": "Invalid project plan."
            }

        files = plan.get("files", [])

        if not files:
            return {
                "success": False,
                "message": "Project plan contains no files."
            }

        generated = {}

        for file_name in files:
            generated[file_name] = self.generate_file(
                file_name,
                plan
            )

        return {
            "success": True,
            "project_name": project_name,
            "files": generated
        }

    # =========================================================
    # GENERATE FILE
    # =========================================================

    def generate_file(self, file_name, plan):

        path = Path(file_name)
        name = path.name.lower()
        suffix = path.suffix.lower()

        if name == "readme.md":
            return self.generate_readme(plan)

        if "tests" in path.parts and suffix == ".py":
            return self.generate_test_file()

        if suffix == ".py":
            return self.generate_python_file(
                path.name,
                plan.get("features", [])
            )

        return (
            "# Generated by AURA\n"
            f"# File: {file_name}\n"
        )

    # =========================================================
    # PYTHON FILE GENERATOR
    # =========================================================

    def generate_python_file(self, file_name, features):

        templates = {

            "main.py": '''from database import Database
from inventory import Inventory
from billing import Billing
from reports import Reports


def main():

    print("AURA Inventory Billing Software")
    print("--------------------------------")

    database = Database()
    inventory = Inventory()
    billing = Billing()
    reports = Reports()

    database.connect()

    inventory.add_product(
        "Sample Product",
        10,
        100.0
    )

    total = billing.calculate_total(
        100.0,
        18.0
    )

    print("Product added successfully.")
    print("Bill Total:", total)

    print("Sales Records:", reports.count())

    database.close()

    print("Application started successfully.")


if __name__ == "__main__":
    main()
''',

            "database.py": '''import sqlite3


class Database:

    def __init__(self, database_name="aura_inventory.db"):
        self.database_name = database_name
        self.connection = None

    def connect(self):

        self.connection = sqlite3.connect(
            self.database_name
        )

        self.create_tables()

        return self.connection

    def create_tables(self):

        if self.connection is None:
            return

        cursor = self.connection.cursor()

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS products (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                quantity INTEGER NOT NULL,
                price REAL NOT NULL
            )
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS customers (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                phone TEXT
            )
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS sales (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                customer_name TEXT,
                total REAL NOT NULL
            )
        """)

        self.connection.commit()

    def close(self):

        if self.connection:
            self.connection.close()
            self.connection = None
''',

            "models.py": '''class Product:

    def __init__(
        self,
        name,
        quantity=0,
        price=0.0
    ):

        self.name = name
        self.quantity = quantity
        self.price = price


class Customer:

    def __init__(
        self,
        name,
        phone=""
    ):

        self.name = name
        self.phone = phone
''',

            "inventory.py": '''class Inventory:

    def __init__(self):

        self.products = {}

    def add_product(
        self,
        name,
        quantity,
        price
    ):

        self.products[name] = {
            "quantity": quantity,
            "price": price
        }

    def update_stock(
        self,
        name,
        quantity
    ):

        if name not in self.products:
            raise ValueError(
                "Product not found."
            )

        self.products[name]["quantity"] += quantity

    def get_product(self, name):

        return self.products.get(name)

    def get_stock(self, name):

        product = self.get_product(name)

        if product is None:
            return 0

        return product["quantity"]
''',

            "stock.py": '''class Stock:

    def __init__(self):

        self.items = {}

    def add(
        self,
        product,
        quantity
    ):

        self.items[product] = (
            self.items.get(product, 0)
            + quantity
        )

    def remove(
        self,
        product,
        quantity
    ):

        current = self.items.get(
            product,
            0
        )

        if quantity > current:
            raise ValueError(
                "Insufficient stock."
            )

        self.items[product] = (
            current - quantity
        )

    def get(self, product):

        return self.items.get(
            product,
            0
        )
''',

            "billing.py": '''class Billing:

    def calculate_subtotal(
        self,
        price,
        quantity
    ):

        return price * quantity

    def calculate_tax(
        self,
        amount,
        tax_rate=0
    ):

        return amount * tax_rate / 100

    def calculate_total(
        self,
        amount,
        tax=0
    ):

        return amount + tax
''',

            "invoice.py": '''class Invoice:

    def create(
        self,
        customer_name,
        items
    ):

        total = 0

        for item in items:
            total += (
                item["price"]
                * item["quantity"]
            )

        return {
            "customer": customer_name,
            "items": items,
            "total": total
        }

    def print_invoice(self, invoice):

        print()
        print("AURA INVOICE")
        print("------------")
        print(
            "Customer:",
            invoice["customer"]
        )

        print(
            "Total:",
            invoice["total"]
        )
''',

            "reports.py": '''class Reports:

    def __init__(self):

        self.sales = []

    def add_sale(self, amount):

        self.sales.append(amount)

    def count(self):

        return len(self.sales)

    def total_sales(self):

        return sum(self.sales)

    def summary(self):

        return {
            "transactions": self.count(),
            "total_sales": self.total_sales()
        }
''',

            "voice.py": '''class VoiceInterface:

    def listen(self):

        return ""

    def speak(self, text):

        print(text)

    def process_command(self, command):

        return command.strip()
''',

            "auth.py": '''class Authentication:

    def login(
        self,
        username,
        password
    ):

        return bool(
            username and password
        )
''',

            "dashboard.py": '''class Dashboard:

    def render(self):

        return "AURA Dashboard"
''',

            "api.py": '''def health():

    return {
        "status": "ok"
    }
''',

            "ai_engine.py": '''class AIEngine:

    def process(self, text):

        return {
            "input": text,
            "response": text
        }
''',

            "payment.py": '''class Payment:

    def process(self, amount):

        return {
            "success": True,
            "amount": amount
        }
''',

            "export.py": '''class Exporter:

    def export(self, data):

        return data
''',

            "config.py": '''APP_NAME = "AURA Inventory Billing Software"

DATABASE_NAME = "aura_inventory.db"
''',

        }

        if file_name in templates:
            return templates[file_name]

        return (
            '"""Generated by AURA."""\n\n'
        )

    # =========================================================
    # TEST FILE
    # =========================================================

    def generate_test_file(self):

        return '''from billing import Billing
from inventory import Inventory
from invoice import Invoice


def test_billing():

    billing = Billing()

    assert billing.calculate_subtotal(
        100,
        2
    ) == 200


def test_inventory():

    inventory = Inventory()

    inventory.add_product(
        "Tea",
        10,
        20
    )

    assert inventory.get_stock(
        "Tea"
    ) == 10


def test_invoice():

    invoice = Invoice()

    result = invoice.create(
        "Test Customer",
        [
            {
                "name": "Tea",
                "price": 20,
                "quantity": 2
            }
        ]
    )

    assert result["total"] == 40
'''

    # =========================================================
    # README
    # =========================================================

    def generate_readme(self, plan):

        project_type = plan.get(
            "project_type",
            "software_application"
        )

        technologies = ", ".join(
            plan.get(
                "technologies",
                []
            )
        )

        features = ", ".join(
            plan.get(
                "features",
                []
            )
        )

        return f"""# AURA Inventory Billing Software

## Project Type

{project_type}

## Technology

{technologies}

## Features

{features}

## Modules

- Database
- Product Management
- Inventory Management
- Stock Management
- Customer Management
- Billing
- Invoice
- Sales Reports
- Automated Testing

## Generated By

AURA Autonomous Developer
"""

    # =========================================================
    # DISPLAY
    # =========================================================

    def display_generated_files(self, generated):

        if not generated.get("success"):

            print(
                "❌",
                generated.get(
                    "message",
                    "Generation failed."
                )
            )

            return

        print()
        print("💻 GENERATED FILES")
        print("==============================")

        for file_name, content in generated[
            "files"
        ].items():

            print()
            print("📄", file_name)
            print(
                "   Lines:",
                len(content.splitlines())
            )


# =============================================================
# TEST
# =============================================================

if __name__ == "__main__":

    print()
    print("======================================")
    print(" AURA CODE GENERATION ENGINE TEST")
    print("======================================")

    from .requirement_analyzer import (
        RequirementAnalyzer
    )

    from .project_planner import (
        ProjectPlanner
    )

    analyzer = RequirementAnalyzer()
    planner = ProjectPlanner()
    generator = CodeGenerationEngine()

    requirement = (
        "Create a complete Python inventory "
        "billing software with database, "
        "reports and automated testing"
    )

    print()
    print("👤 REQUIREMENT:")
    print(requirement)

    analysis = analyzer.analyze(
        requirement
    )

    plan = planner.create_plan(
        analysis
    )

    print()
    print("📐 PLAN CREATED")

    generated = generator.generate_project(
        plan,
        "aura_inventory_app"
    )

    generator.display_generated_files(
        generated
    )

    print()
    print("======================================")
    print(" ✅ CODE GENERATION ENGINE TEST COMPLETE")
    print("======================================")