from pathlib import Path
import subprocess
import sys


class ProjectBuilder:

    def __init__(self, workspace="workspace"):
        self.workspace = Path(workspace)
        self.workspace.mkdir(
            parents=True,
            exist_ok=True
        )

        print("🏗️ Project Builder: READY")

    def build_calculator(
        self,
        project_name="aura_smart_calculator"
    ):

        project_path = (
            self.workspace / project_name
        )

        project_path.mkdir(
            parents=True,
            exist_ok=True
        )

        tests_path = (
            project_path / "tests"
        )

        tests_path.mkdir(
            parents=True,
            exist_ok=True
        )

        calculator_code = """class Calculator:

    def add(self, a, b):
        return a + b

    def subtract(self, a, b):
        return a - b

    def multiply(self, a, b):
        return a * b

    def divide(self, a, b):

        if b == 0:
            raise ValueError("Cannot divide by zero.")

        return a / b
"""

        main_code = """from calculator import Calculator


def main():

    calculator = Calculator()

    print("AURA Smart Calculator")
    print("---------------------")

    print(
        "Addition:",
        calculator.add(10, 5)
    )

    print(
        "Subtraction:",
        calculator.subtract(10, 5)
    )

    print(
        "Multiplication:",
        calculator.multiply(10, 5)
    )

    print(
        "Division:",
        calculator.divide(10, 5)
    )


if __name__ == "__main__":
    main()
"""

        test_code = """import sys
from pathlib import Path

sys.path.insert(
    0,
    str(Path(__file__).resolve().parents[1])
)

from calculator import Calculator


def test_add():

    calc = Calculator()

    assert calc.add(10, 5) == 15


def test_subtract():

    calc = Calculator()

    assert calc.subtract(10, 5) == 5


def test_multiply():

    calc = Calculator()

    assert calc.multiply(10, 5) == 50


def test_divide():

    calc = Calculator()

    assert calc.divide(10, 5) == 2


def test_divide_by_zero():

    calc = Calculator()

    try:
        calc.divide(10, 0)

    except ValueError:
        assert True

    else:
        assert False
"""

        readme_code = f"""# {project_name}

## AURA Smart Software Developer

Generated by AURA Project Builder.

## Features

- Addition
- Subtraction
- Multiplication
- Division
- Division-by-zero protection
- Automated tests
"""

        files = {
            "calculator.py": calculator_code,
            "main.py": main_code,
            "README.md": readme_code,
            "tests/test_calculator.py": test_code
        }

        created_files = []

        for relative_path, content in files.items():

            file_path = (
                project_path / relative_path
            )

            file_path.parent.mkdir(
                parents=True,
                exist_ok=True
            )

            file_path.write_text(
                content,
                encoding="utf-8"
            )

            created_files.append(
                str(file_path)
            )

        return {
            "project_path": str(
                project_path.resolve()
            ),
            "files": created_files
        }

    def validate_project(
        self,
        project_path
    ):

        project_path = Path(
            project_path
        ).resolve()

        python_files = list(
            project_path.rglob("*.py")
        )

        errors = []

        for file_path in python_files:

            result = subprocess.run(
                [
                    sys.executable,
                    "-m",
                    "py_compile",
                    str(file_path)
                ],
                capture_output=True,
                text=True
            )

            if result.returncode != 0:

                errors.append({
                    "file": str(file_path),
                    "error": result.stderr.strip()
                })

        if errors:
            return False, errors

        return True, python_files

    def run_application(
        self,
        project_path
    ):

        project_path = Path(
            project_path
        ).resolve()

        main_file = (
            project_path / "main.py"
        )

        if not main_file.exists():
            return False, "main.py not found."

        result = subprocess.run(
            [
                sys.executable,
                "main.py"
            ],
            cwd=str(project_path),
            capture_output=True,
            text=True,
            timeout=30
        )

        if result.returncode == 0:

            return True, result.stdout.strip()

        return False, result.stderr.strip()

    def run_tests(
        self,
        project_path
    ):

        project_path = Path(
            project_path
        ).resolve()

        tests_path = (
            project_path / "tests"
        )

        if not tests_path.exists():
            return False, "Tests directory not found."

        result = subprocess.run(
            [
                sys.executable,
                "-m",
                "pytest",
                "-q"
            ],
            cwd=str(project_path),
            capture_output=True,
            text=True,
            timeout=60
        )

        output = (
            result.stdout.strip()
            + "\n"
            + result.stderr.strip()
        ).strip()

        if result.returncode == 0:
            return True, output

        return False, output


if __name__ == "__main__":

    print()
    print("======================================")
    print(" AURA PROJECT BUILDER TEST")
    print("======================================")
    print()

    builder = ProjectBuilder()

    print("🏗️ Building project...")

    result = builder.build_calculator()

    project_path = result["project_path"]

    print()
    print("📁 PROJECT:")
    print(project_path)

    print()
    print("📄 CREATED FILES:")

    for file in result["files"]:
        print("   └──", file)

    print()
    print("🧪 VALIDATING PROJECT...")

    valid, validation_result = (
        builder.validate_project(
            project_path
        )
    )

    if not valid:

        print("❌ VALIDATION FAILED")

        for error in validation_result:

            print(error["file"])
            print(error["error"])

        raise SystemExit(1)

    print("✅ ALL PYTHON FILES VALID")

    print()
    print("🚀 RUNNING APPLICATION...")

    success, output = (
        builder.run_application(
            project_path
        )
    )

    if not success:

        print("❌ APPLICATION FAILED")
        print(output)

        raise SystemExit(1)

    print("✅ APPLICATION RUN SUCCESSFULLY")
    print()
    print(output)

    print()
    print("🧪 RUNNING AUTOMATED TESTS...")

    success, test_output = (
        builder.run_tests(
            project_path
        )
    )

    if not success:

        print("❌ TESTS FAILED")
        print()
        print(test_output)

        raise SystemExit(1)

    print("✅ ALL TESTS PASSED")
    print()
    print(test_output)

    print()
    print("======================================")
    print(" ✅ PROJECT BUILDER SUCCESS")
    print("======================================")